      - name: Test `set_env=false`
        id: set-env-false # a step 'id' must be set in order to access the secrets with set_env=false
        uses: bitwarden/sm-action@v3.0.0-beta.3
        with:
          access_token: ${{ secrets.TEST_SM_ACCESS_TOKEN_EU }}
          cloud_region: eu
          set_env: false # we have told the sm-action to not set the secrets as env vars
           secrets: |
            1dabf2d1-b80e-4f2f-9fe3-992e48e3874e > TEST_SECRETS_1
            a7131ad8-5476-4b90-87f0-13d1e3804ac0 > TEST_SECRETS_2

      - name: Ensure that `set_env=false` works correctly
        run: |
          echo set_env is false, so secrets should not be in env:
          if [ -n "$SECRET_NO_ENV_ONE" ] || [ -n "$SECRET_NO_ENV_TWO" ]; then
            echo "Secrets found in environment variables, but set_env is false" >&2
            exit 1
          else
            echo "No secrets found in environment variables, as expected"
          fi
          echo
          echo printing unmasked secrets with spaces between each character from GITHUB_OUTPUT:
          echo "${{ steps.set-env-false.outputs.SECRET_NO_ENV_ONE }}" | sed 's/./& /g'
          echo "${{ steps.set-env-false.outputs.SECRET_NO_ENV_TWO }}" | sed 's/./& /g'
          echo
