name: Test the new sm-action

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test Rust sm-action
    runs-on: ubuntu-24.04
    steps:
      - name: Test sm-action v3.0.0-beta.4
        id: secrets
        uses: bitwarden/sm-action@v3.0.0-beta.4
        with:
          access_token: ${{ secrets.TEST_SM_ACCESS_TOKEN_EU }}
          cloud_region: EU
          secrets: |
            1dabf2d1-b80e-4f2f-9fe3-992e48e3874e > TEST_SECRETS_1
            a7131ad8-5476-4b90-87f0-13d1e3804ac0 > TEST_SECRETS_2

      - name: Test env vars are set
        run: |
          echo "SECRET_ONE=$SECRET_ONE"
          echo "SECRET_TWO=$SECRET_TWO"
          echo
  # the following will inject spaces between each character in the secret,
  # allowing us to verify that the secrets are set properly:
          echo "$SECRET_ONE" | sed 's/./& /g'
          echo "$SECRET_TWO" | sed 's/./& /g'
          echo