name: Test Stuff

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Test sm-action 3.0.0-beta.2
    runs-on: windows-11-arm
    steps:
      - name: Test sm-action 3.0.0-beta.2
        id: secrets
        uses: bitwarden/sm-action@v3.0.0-beta.2
        with:
          access_token: ${{ secrets.TEST_SM_ACCESS_TOKEN }}
          api_url: "https://api.qa.bitwarden.pw"
          identity_url: "https://identity.qa.bitwarden.pw"
          secrets: |
            0bffbb23-cd39-49f5-8b54-b34d0189810e >> SECRET_ONE
            a6d3aa16-b6bc-4af7-9345-b3a8013a4ba0 >> SECRET_TWO

      - name: Test env vars are set
        run: |
          Write-Host "SECRET_ONE=$SECRET_ONE"
          Write-Host "SECRET_TWO=$SECRET_TWO"
          Write-Host

          Write-Output $env.SECRET_ONE
          Write-Output $env.SECRET_TWO
          Write-Host
